### ISSUE TITLE
My training on my customized dataset has no effect

### ISSUE THREAD

**Issue by melonyxin** [GiovanniPasq/DA-Faster-RCNN#1]
I trained 3w iterations on my customized dataset, but the test result （mAP50）is only 2%. Why？

**Comment by GiovanniPasq** [comment]
Hello, 
which are the performance of standard faster rcnn on your dataset?

**Comment by melonyxin** [comment]
Thanks for your reply.
The test result can reach 52% on souce-only.
There is no network configuration changes just change the datasets.
From 5k iterations to 3w iterations, all the test result are about 1~3%.
I will try to increase the parameters, hope it will handle this.

**Comment by GiovanniPasq** [comment]
I suggest you increase the lambda vaule (0.1 in the code) by 0.2 in each experiment (0.3, 0.5, 0.7, 0.9 and 1) and see if the performance become better. The max value is 1, if this does not effect the model performance let me know.
