### ISSUE TITLE
Training is success but test has an error

### ISSUE THREAD

**Issue by Nurungyi** [GiovanniPasq/DA-Faster-RCNN#11]
I tried to understand DA-Faster R-CNN, authors with your well-made code.

I did download your code, and replace detectron2 it yours.
I successfully train the model but when I tried to do test using the generated model, the following error occurs:

# test
cfg_source = get_cfg()
# cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml"))
cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"))

cfg_source.MODEL.WEIGHTS = os.path.join(cfg_source.OUTPUT_DIR, "model_final.pth")
cfg_source.DATASETS.TEST = ("target_test",)

# cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128
cfg_source.MODEL.ROI_HEADS.NUM_CLASSES = 2
cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 

predictor = DefaultPredictor(cfg_source)

build_resnet_backbone
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[17], line 13
     10 cfg_source.MODEL.ROI_HEADS.NUM_CLASSES = 2
     11 cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 
---> 13 predictor = DefaultPredictor(cfg_source)

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/engine/defaults.py:282, in DefaultPredictor.__init__(self, cfg)
    280 def __init__(self, cfg):
    281     self.cfg = cfg.clone()  # cfg can be modified by model
--> 282     self.model = build_model(self.cfg)
    283     self.model.eval()
    284     if len(cfg.DATASETS.TEST):

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/modeling/meta_arch/build.py:22, in build_model(cfg)
     17 """
     18 Build the whole model architecture, defined by ``cfg.MODEL.META_ARCHITECTURE``.
     19 Note that it does not load any weights from ``cfg``.
     20 """
     21 meta_arch = cfg.MODEL.META_ARCHITECTURE
---> 22 model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
     23 model.to(torch.device(cfg.MODEL.DEVICE))
     24 _log_api_usage("modeling.meta_arch." + meta_arch)

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/config/config.py:190, in configurable.<locals>.wrapped(self, *args, **kwargs)
    188 if _called_with_cfg(*args, **kwargs):
    189     explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
--> 190     init_func(self, **explicit_args)
    191 else:
    192     init_func(self, *args, **kwargs)

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/modeling/meta_arch/rcnn.py:68, in GeneralizedRCNN.__init__(self, backbone, proposal_generator, roi_heads, pixel_mean, pixel_std, input_format, vis_period, model_weights)
     66     self.backbone_name = "C4"
     67     self.dim_in_feature_discriminator = 1024
---> 68 self.discriminator = Discriminator(self.dim_in_feature_discriminator)
     70 self.input_format = input_format
     71 self.vis_period = vis_period

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1612     if name in modules:
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'GeneralizedRCNN' object has no attribute 'dim_in_feature_discriminator'

Can you give the guideline for solving this?

**Comment by GiovanniPasq** [comment]
Hello,
another user also reported this problem and for this reason I released a patch last week, unfortunately it was a bug. In particular within the rcnn.py script replace this block:
```
if "FPN" in model_weights:
            self.backbone_name = "FPN"
            self.dim_in_feature_discriminator = 256
        elif "DC5" in model_weights:
            self.backbone_name = "DC5"
            self.dim_in_feature_discriminator = 2048
        elif "C4" in model_weights:
            self.backbone_name = "C4"
            self.dim_in_feature_discriminator = 1024
        self.discriminator = Discriminator(self.dim_in_feature_discriminator)
```

with the following one:
```
if self.training:
      if "FPN" in model_weights:
          self.backbone_name = "FPN"
          self.dim_in_feature_discriminator = 256
      elif "DC5" in model_weights:
          self.backbone_name = "DC5"
          self.dim_in_feature_discriminator = 2048
      elif "C4" in model_weights:
          self.backbone_name = "C4"
          self.dim_in_feature_discriminator = 1024
      self.discriminator = Discriminator(self.dim_in_feature_discriminator)
```
Otherwise you can download the new rcnn.py script and replace the older one

**Comment by Nurungyi** [comment]
Thank you for your swift response. I re-download the pathced version, and then only replace the exsting rcnn.py in previous version with new verion updated in last week (recent version), but still the following problem occurs:

build_resnet_backbone
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[19], line 13
     10 cfg_source.MODEL.ROI_HEADS.NUM_CLASSES = 2
     11 cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 
---> 13 predictor = DefaultPredictor(cfg_source)

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/engine/defaults.py:282, in DefaultPredictor.__init__(self, cfg)
    280 def __init__(self, cfg):
    281     self.cfg = cfg.clone()  # cfg can be modified by model
--> 282     self.model = build_model(self.cfg)
    283     self.model.eval()
    284     if len(cfg.DATASETS.TEST):

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/modeling/meta_arch/build.py:22, in build_model(cfg)
     17 """
     18 Build the whole model architecture, defined by ``cfg.MODEL.META_ARCHITECTURE``.
     19 Note that it does not load any weights from ``cfg``.
     20 """
     21 meta_arch = cfg.MODEL.META_ARCHITECTURE
---> 22 model = META_ARCH_REGISTRY.get(meta_arch)(cfg)
     23 model.to(torch.device(cfg.MODEL.DEVICE))
     24 _log_api_usage("modeling.meta_arch." + meta_arch)

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/config/config.py:190, in configurable.<locals>.wrapped(self, *args, **kwargs)
    188 if _called_with_cfg(*args, **kwargs):
    189     explicit_args = _get_args_from_config(from_config_func, *args, **kwargs)
--> 190     init_func(self, **explicit_args)
    191 else:
    192     init_func(self, *args, **kwargs)

File ~/Desktop/Seunghyeon/DA-Faster R-CNN/detectron2/detectron2/modeling/meta_arch/rcnn.py:70, in GeneralizedRCNN.__init__(self, backbone, proposal_generator, roi_heads, pixel_mean, pixel_std, input_format, vis_period, model_weights)
     68         self.backbone_name = "C4"
     69         self.dim_in_feature_discriminator = 1024
---> 70     self.discriminator = Discriminator(self.dim_in_feature_discriminator)
     72 self.input_format = input_format
     73 self.vis_period = vis_period

File ~/Desktop/Seunghyeon/hanyang/lib/python3.10/site-packages/torch/nn/modules/module.py:1614, in Module.__getattr__(self, name)
   1612     if name in modules:
   1613         return modules[name]
-> 1614 raise AttributeError("'{}' object has no attribute '{}'".format(
   1615     type(self).__name__, name))

AttributeError: 'GeneralizedRCNN' object has no attribute 'dim_in_feature_discriminator'

Except for replacing it, is there any replacement?

**Comment by GiovanniPasq** [comment]
Can you try to delete the python cache? it should work if you have downloaded and replaced the latest version of rcnn.py. Another solution is to rename the weights that you have saved including in their name the name of the backbone that you used during the training. So if you are using the C4 backbone, try to rename the pth file as "C4_model_final.pth" and try to load it

**Comment by Nurungyi** [comment]
I did initial the cache, but did not work. so, uninstall and re-install detectron2, and then overlap it again but still did not work. I think that I will tried to install to another computer if it is problem for current computer.

**Comment by GiovanniPasq** [comment]
Before installing in other pc, try to rename the new weights as i suggested

**Comment by Nurungyi** [comment]
In your github, you provide DA-Faster-RCNN.ipynb. Based on these, I tailored to my dataset.
The below code does work.

#COCO evaluation example
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
evaluator = COCOEvaluator("target_test", cfg_source, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg_source, "target_test")
inference_on_dataset(model, val_loader, evaluator)


but, when I tried to use the following code, and error occurs same as above error that I mentioned previously:

    # test
    cfg_source = get_cfg()
    cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"))

    cfg_source.MODEL.WEIGHTS = os.path.join(cfg_source.OUTPUT_DIR, "model_final.pth")
    cfg_source.DATASETS.TEST = ("target_test",)

    cfg_source.MODEL.ROI_HEADS.NUM_CLASSES = 2
    cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 

    predictor = DefaultPredictor(cfg_source)


I think that "DefaultPredictor" may be not compatible with recent rcnn.py. Could you please test it on your environment using "DefaultPredictor"?

**Comment by GiovanniPasq** [comment]
Hello,
i tested the code with my environment and it works. If you need to compute the mAP to evaluate the model you need to run the code that you can find at the end of the notebook or at the end of the uda_train.py script.
If you need a visual output you can just run the following code:
```
import cv2
im = cv2.imread("./input.jpg")
cv2_imshow(im)
predictor = DefaultPredictor(cfg_source)
outputs = predictor(im)
```

**Comment by GiovanniPasq** [comment]
Hello,
I tried on my environment and got the same error as yours, a quick fix is to rename the .pth file that you are trying to load.
If you are using faster_rcnn_R_50_C4_1x.yam, rename the pth file that you obtained at the end of the training including the name of the backbone in the file. 
Example:
faster_rcnn_R_50_C4_1x -> C4_model_final.pth
faster_rcnn_R_50_FPN_1x -> FPN_model_final.pth
faster_rcnn_R_50_DC5_1x -> DC5_model_final.pth

**Comment by Nurungyi** [comment]
When I tried to modify the examples provided above, I encountered some inconsistencies. Some name changes worked, while others didn't. Here are the results:
 
1) Renaming 'faster_rcnn_R_50_C4_1x' to 'C4_model_final.pth' worked.
2) Renaming 'faster_rcnn_R_50_C4_1x' to 'FPN_model_final.pth' worked.
3) Renaming 'faster_rcnn_R_50_C4_1x' to 'C5_model_final.pth' did not work.
4) Renaming 'faster_rcnn_R_50_C4_1x' to 'aaa_model_final.pth' did not work.
5) Renaming 'faster_rcnn_R_50_C4_1x' to 'FPM_model_final.pth' did not work.

Should I match the pre-fix (e.g. C4 or FPN) to model_final.pth?

**Comment by GiovanniPasq** [comment]
Hello, 
Probably i did not explained well myself in the previoua message. You need to rename the final pth file that you obtain at the end of your training.
Example:
```
cfg_source = get_cfg()
cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"))
cfg_source.MODEL.WEIGHTS = os.path.join(cfg_source.OUTPUT_DIR, "C4_model_final.pth")
```
You must add the prefix in the final .pth file according with the file yaml that you are using inside the function "merge_from_file". If you use FPN or DC5 you need to do the same

**Comment by Nurungyi** [comment]
Thank you for your effort.

**Comment by GiovanniPasq** [comment]
you're welcome, if you have other problems feel free to open other issues, i will try to help you :)
