### ISSUE TITLE
Training is success with custom dataset but test accuracy is 0

### ISSUE THREAD

**Issue by aybukesakaci** [GiovanniPasq/DA-Faster-RCNN#13]
Hello, 

I have questions about the implementation of your work. I used custom dataset. I successfully train the model but when I tried to do test using the generated model, i have no error but the test accuracy is always 0. For testing i am using COCOEvaluator part. And also i tried to test with this code:

# test
cfg_source = get_cfg()
cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"))

cfg_source.MODEL.WEIGHTS = os.path.join(cfg_source.OUTPUT_DIR, "C4_model_final.pth")
cfg_source.DATASETS.TEST = ("target_test",)

cfg_source.MODEL.ROI_HEADS.NUM_CLASSES = 1
cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 

predictor = DefaultPredictor(cfg_source)

The result is same :(

Could you have the solution for the problem? And also what is your test accuracy for your own case?

Thank you in advance.

**Comment by GiovanniPasq** [comment]
Hello,
if you are interested to compute the accuracy of the model (mAP 50) you need to remove the instruction:
```
cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5
```
and run the following code: 
```
#COCO evaluation
from detectron2.evaluation import COCOEvaluator, inference_on_dataset
evaluator = COCOEvaluator("balloon_test", cfg_source, False, output_dir="./output/")
val_loader = build_detection_test_loader(cfg_source, "target_test")
inference_on_dataset(model, val_loader, evaluator)
```

if you are interested in the visual output, the code should be something like this:
```
import detectron2

# import some common libraries
import numpy as np
import os, json, cv2, random
from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer

im = cv2.imread("./input.jpg") #your image
cv2_imshow(im)

cfg_source = get_cfg()
cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"))
cfg_source.MODEL.WEIGHTS =  os.path.join(cfg_source.OUTPUT_DIR, "C4_model_final.pth")
cfg_source.INPUT.MIN_SIZE_TEST = 0 
cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model 
predictor = DefaultPredictor(cfg_source)
outputs = predictor(im)

v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2_imshow(out.get_image()[:, :, ::-1])
```

**Comment by GiovanniPasq** [comment]
i updated the colab notebook with better information. You can find it here:
https://colab.research.google.com/gist/GiovanniPasq/9c0e99cde5df9aa09e3aff3295637a61/da-faster-rcnn.ipynb
