### ISSUE TITLE
How does the code add loss_Image_d and loss_Instance_d to the total losses dictionary:loss_dict and loss_dict_target?

### ISSUE THREAD

**Issue by yzy3314992** [GiovanniPasq/DA-Faster-RCNN#15]

**Comment by yzy3314992** [comment]
I noticed that there is loss=[] related loss function dictionary construction in the rcnn.py file, but how does the code pass the losses dictionary to loss_dict and loss_dict_target?I would be grateful if the author could provide an answer.

**Comment by GiovanniPasq** [comment]
Hello,
in the rcnn.py file the loss_instance_d loss has been added using (rows 199-200):
```
...
losses.update(loss_discriminator)
losses["loss_instance_d"] = losses.pop("loss_instance_d")
```
You can find the other usage searching the keyword loss_instance_d in rcnn.py.

In the roi_heads.py file the loss_image_d loss has been added using (rows 472):
```
...
losses.update(loss_discriminatorProposal)
```
You can find the other usage searching the keyword loss_discriminatorProposal in roi_heads.py.

Greetings.

**Comment by yzy3314992** [comment]
thank you for your reply! Your code is really great, I wonder if you mean adding loss_image_d in rcnn.py and loss_instance_d in roi_head.py, because I noticed that the Class Discriminator code and the Class DiscriminatorProposal code correspond to the calculation of loss_image_d and loss_instance_d respectively. 

Also, if I want to add a new loss in the loss_dict at the instance-level aligned level without using gradient reverse layer, is it possible to add `losses["new_loss"] = losses.pop("new_loss")` in the rcnn.py file code, and add the `losses.update(new_loss)` code in the roi_head.py file to add the new loss to the loss_dict? 

Because I don't know much about the process from losses to loss_dict and loss_dict_target.Thank you very much.

**Comment by GiovanniPasq** [comment]
loss_dict is a dictionary and contains the losses computed using the source images. using the function ```.update()``` you will add to the dictionary a new element.
