### ISSUE TITLE
How to implement the source-only comparative experiment part of the original paper in this code？

### ISSUE THREAD

**Issue by yzy3314992** [GiovanniPasq/DA-Faster-RCNN#16]
Hello author! Thanks for the code! If I want to implement the "source-only" item in the experimental table of the original paper, how should I modify the uda_train.py file of this code?

**Comment by GiovanniPasq** [comment]
Hello,
from what I've read, I think you should study the problem and the definition of unsupervised domain adaptation more thoroughly. This is the implementation of Da-Faster R-CNN. The source-only experiments correspond to the Faster R-CNN trained with the source domain and tested with the target without using any domain adaptation technique.
Regards.
