### ISSUE TITLE
May I ask if you have used mmdet?

### ISSUE THREAD

**Issue by bigdiok** [GiovanniPasq/DA-Faster-RCNN#18]
I noticed that you modified this code on Detectron2. I would like to ask if you can also do the same on mmdet to get DA-Faster-RCNN?

**Comment by GiovanniPasq** [comment]
Hello,
it is possible to implement DA-Faster-RCNN on mmdet as well. However, I have recently shifted my research focus, and unfortunately, I don't have the time to thoroughly study the mmdet framework to implement the necessary modifications.
kind regards

**Comment by bigdiok** [comment]
> Hello, it is possible to implement DA-Faster-RCNN on mmdet as well. However, I have recently shifted my research focus, and unfortunately, I don't have the time to thoroughly study the mm

> Hello, it is possible to implement DA-Faster-RCNN on mmdet as well. However, I have recently shifted my research focus, and unfortunately, I don't have the time to thoroughly study the mmdet framework to implement the necessary modifications. kind regards

thank you！
