### ISSUE TITLE
 the installation of Detectron2 did not complete successfully

### ISSUE THREAD

**Issue by TahereSaidi** [GiovanniPasq/DA-Faster-RCNN#4]
Hello. thanks for your work!
Can we use this model when we don't have a labels in the target domain?

**Comment by GiovanniPasq** [comment]
Hello, I tried to install detectron2 using the instructions inside my notebook and the installation was successful, it takes a couple of minutes.

Yes you can use the model when you do not have the labels in the target domain. Add this line  ```cfg_target.DATALOADER.FILTER_EMPTY_ANNOTATIONS = False``` to the script after the instruction 
```cfg_target.INPUT.MIN_SIZE_TRAIN =(600,)```

**Comment by TahereSaidi** [comment]
When I run this command:
!python -m pip install pyyaml==5.1
!python -m pip install 'git+https://github.com/facebookresearch/detectron2.git'
exit(0)
 the file comes to this address:
 [/usr/local/lib/python3.7/dist-packages/detectron2/modeling/meta_arch]
 But my question is, is it possible to make the file to be saved in Google Drive instead of going to this address? So that after I apply the mentioned changes, it will be saved and won't be lost by closing the colab?

**Comment by GiovanniPasq** [comment]
Unfortunatelly you cannot change the files destination, the changes won't be saved when you close the colab :(

**Comment by TahereSaidi** [comment]
Thank you for your attention.
My last question is that when I run these lines, I have Python 3.10 at this address and the detectron2 comes here, is there any problem that Python 3.7 is not created for me?

**Comment by GiovanniPasq** [comment]
No it's not a problem, the python version can change but you need to replace the file according to your installed version. Your path should be 
```../usr/local/lib/python3.10/dist-packages/detectron2```

**Comment by TahereSaidi** [comment]
yes. thank you so much.

**Comment by GiovanniPasq** [comment]
You are welcome, i am closing the issue, if you have other problem reopen it. If you could leave a star it can help to grow up the repo :)
