### ISSUE TITLE
Visual results

### ISSUE THREAD

**Issue by TahereSaidi** [GiovanniPasq/DA-Faster-RCNN#7]
Hi
How can we display the results of the algorithm visually?
That is, after running the algorithm on my dataset, I want to see the results that include the binding boxes

**Comment by GiovanniPasq** [comment]
Hello,
you can find an example inside the official Detectron2 Colab Notebook at this link:
```https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5```

The code should be something like this:

```
import detectron2

# import some common libraries
import numpy as np
import os, json, cv2, random
from google.colab.patches import cv2_imshow

# import some common detectron2 utilities
from detectron2 import model_zoo
from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2.utils.visualizer import Visualizer

im = cv2.imread("./input.jpg") #your image
cv2_imshow(im)

cfg_source = get_cfg()
cfg_source.merge_from_file(model_zoo.get_config_file("COCO-Detection/faster_rcnn_R_50_C4_1x.yaml"))
cfg_source.DATASETS.TRAIN = #your dataset
cfg_source.MODEL.WEIGHTS = #your weights
cfg_source.INPUT.MIN_SIZE_TEST = 0 
cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
predictor = DefaultPredictor(cfg_source)
outputs = predictor(im)

v = Visualizer(im[:, :, ::-1], MetadataCatalog.get(cfg.DATASETS.TRAIN[0]), scale=1.2)
out = v.draw_instance_predictions(outputs["instances"].to("cpu"))
cv2_imshow(out.get_image()[:, :, ::-1])
```

**Comment by TahereSaidi** [comment]
"cfg_source.MODEL.WEIGHTS = #your weights"
Thank you very much for your attention
When I trained the model myself, in which part are the weights stored so I can use them?
I have now customized the model and entered the code you put in the next cell. But for the weight part, I don't know where the final model with pth extension is saved to use.
I want to show the results for the test data.

**Comment by GiovanniPasq** [comment]
I do not remember exactly where the weights are saved but they should be saved inside a default folder create by detectron2 called "output" or "checkpoint" (you can find the exact path inside the detectron2 config class). 
Otherwise you can save the model after the do_train() function using:
```
torch.save(model.state_dict(),'yourPath/da_fasterRCNN_weights.pth')
```
and than loading them using 
```
cfg_source.MODEL.WEIGHTS = "yourPath/da_fasterRCNN_weights.pth"
```
Other useful link: https://pytorch.org/tutorials/beginner/saving_loading_models.html

NB: if you do not download or save the weights of your model and you are using the colab notebook you will lose them if you restart it

**Comment by helia-mohamadi** [comment]
Hello again,
I used this code to get the visual results , but I've got this error :


build_resnet_backbone

AttributeError                            Traceback (most recent call last)
<ipython-input-9-06928c81bfc6> in <cell line: 23>()
     21 cfg_source.INPUT.MIN_SIZE_TEST = 0
     22 cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # set threshold for this model
---> 23 predictor = DefaultPredictor(cfg_source)
     24 outputs = predictor(im)
     25 

4 frames
/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
   1612             if name in modules:
   1613                 return modules[name]
-> 1614         raise AttributeError("'{}' object has no attribute '{}'".format(
   1615             type(self).__name__, name))
   1616 

AttributeError: 'GeneralizedRCNN' object has no attribute 'dim_in_feature_discriminator'

**Comment by GiovanniPasq** [comment]
Hello,
i forgot to write that the new weights that you load must include in their name the name of the backbone that you used. So if you use the C4 backbone the name of your weights must include C4 e.g "C4_weight_da_fasterRCNN.pth", if you use the DC5 backbone the name should be something like "DC5_weight_da_fasterRCNN.pth" for the FPN backbone is the same.

I updated the code so that at test time you can name the new weights as you prefer.

**Comment by helia-mohamadi** [comment]
Thank you the error fixed, but It wasn't shown any bounding box.
I think it is because of the accuracy that I've got.

**Comment by GiovanniPasq** [comment]
Which is the Ap do you achieve?

You can change the minimum threshold value to show setting it lower:
cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5  # value must be >=0.1 and <=1

**Comment by helia-mohamadi** [comment]
I trained with 1000 iteration for 2331 synthetic images before you explain the epoch formula and I've got 0.2 AP.

**Comment by GiovanniPasq** [comment]
How many classes do you have in your dataset?  Which is the learning rate and the batch size that you used?
1000 iterations for a dataset with 2331 images is less than 1 epoch of training, i suggest you to train it for 10000 iterations and with a learning rate of 0.0002

**Comment by helia-mohamadi** [comment]
I trained the model with 5828 iterations and lr=0.0002 for 5 classes and I've got these Percents :
AP': 31.925201885510536,
'AP50': 55.94689911930962,
'AP75': 32.776419118960675,

But when I wanted to visualize the detection results, model detected some classes which I didn't have them at all or detect the sky.

**Comment by GiovanniPasq** [comment]
ok the AP that you should consider is the AP50 which is 55.94%. Probably changing the backbone with the FPN and trying different learning rate and more iterations it should achieve higher performance. 

i suggest you to use default (0.5) or higher threshold, lower threshold can produce many false positive in the visual output predictions. 
cfg_source.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.5 

About the classes that the model detects and that are not in your training set, are you sure you are using the new weights and not the initial weights?
