### ISSUE TITLE
Improvement the model

### ISSUE THREAD

**Issue by helia-mohamadi** [GiovanniPasq/DA-Faster-RCNN#8]
Hello again
I wanted to ask you about how to optimize your model compared to the original model and what changes compared to the original source code that have improved the process.
Thank you

**Comment by GiovanniPasq** [comment]
Hello,
the answer to the first question is:
you can optimize the model as follow:
1) inside the do_train function you can increase the alpha factor passed to the model (value must be >0 and <=1):
```
loss_dict = model(data_source, False, 0.5)
loss_dict_target = model(data_target, True, 0.5)
```
2) you can write your own image level discriminator inside the image_level_discriminator.py
3) you can write your own instance level discriminator inside the instance_level_discriminator.py
     
the answer to the second question is:
with the term source code are you referring to the Faster RCNN code or to the DA-FasterRCNN code of the first authors?

**Comment by helia-mohamadi** [comment]
Thank you for your attention,
about your first answer , I will try it thank you.
about your second answer , I mean DA-FasterRCNN  code of the first author.

**Comment by GiovanniPasq** [comment]
I have adapted the two discriminators (instance-level domain classifier and image-level domain classifier) to the Faster Rcnn architecture written in detectron2 so that it can be used with different backbones (c4, d5 and fpn)
